swagger: '2.0'
info:
  description: desc
  version: 1.0.0
  title: Swagger Petstore
host: petstore.swagger.io
basePath: /v1
tags:
  - name: pet
    description: Everything about your Pets
paths:
  /v1/conversion/cancel:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      description: hj
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        '405':
          description: Invalid input
definitions:
  Pet:
    type: object
    required:
      - name
      - photoUrls
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        items:
          type: string
      status:
        type: string
        description: pet status in the store
        enum:
          - available
          - pending
          - sold
